### PR TITLE
Feature/127

### LINKED ISSUE #127: Broken Characters in Navbar and Books Page
From PR #125

I just found two occurrences of cryptic letters, see screenshot. 
crypticLetters
It looks like one of the problems lies in https://github.com/Bantolomeus/bookmaster4000mkii/blob/030d40def1205402d0c07476803c312737ad7f8d/client/src/Books.res#L405 .
Do you call the books object there? If I understood it correctly, then the books should also be blue in the code.
Or lies the problem in https://github.com/Bantolomeus/bookmaster4000mkii/blob/030d40def1205402d0c07476803c312737ad7f8d/client/src/Books.res#L352 
There do not stand the string books, only a dot and for me it looks like the dot is the problem.

Let me know what the problem was and if my second suggestion was right.

I would like to get the cryptic letters fixed before we merge.

_Originally posted by @Bantolomeus in https://github.com/Bantolomeus/bookmaster4000mkii/issues/125#issuecomment-1175410544_

### PR DESCRIPTION
**Pull request by Husterknupp**
@Bantolomeus can you try out the latest build please?

The two weird symbols should be gone and more useful things hopefully will appear. But have a look at the symbol in the Navbar, left to "Challenge". This is the books emoji but in case you're using Chrome on Windows 7, the books emoji will probably be black. In Firefox or when you will finally upgrade your OS the books have colors.

(also the title and the favicon should be back, yey)

closes #127

### CODE REVIEW

**Comment by Bantolomeus** [comment]
I checked out the latest jar, but it looks the same way as before
stillThere

**Comment by Husterknupp** [comment]
When you say the latest jar, you mean from from the commit that's on master?

This one won't have the changes that I made. Please check out the jar from a commit on this branch

**Comment by Husterknupp** [comment]
@Bantolomeus https://github.com/Bantolomeus/bookmaster4000mkii/actions/runs/2677288279 would be the jar from latest commit on the feature branch https://github.com/Bantolomeus/bookmaster4000mkii/commit/57efdb63b6e44596c3f7c87aef5a72337abad303

**Comment by Bantolomeus** [comment]
I used the provided link, but the result is the same:
still

**Comment by Bantolomeus** [comment]
Mein OS:
Win 7 home premium
Service Pack 1

vielleicht liegt es daran, dass ich nicht das Service Pack 2 habe, welches es scheinbar nur mit "bessere" Win 7 Versionen erhaeltlich sind.

**Comment by Bantolomeus** [comment]
Apparently now Emojis show on my firefox. Maybe it is related to one of the latest Windows automatic updates (1.373.157.0 or 1.373.94.0 are the last two MS Security Essentials)

Works on my machine :+1:

**Pull request merged**
